# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/jkali/ece385/lab7/lab7_1/lab7_1.srcs/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_6/mb_usb_hdmi_text_controller_0_6.xci
# IP: The module: 'mb_usb_hdmi_text_controller_0_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/jkali/ece385/lab7/lab7_1/lab7_1.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_6/src/hdmi_tx_0_2/hdmi_tx_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_tx_0 || ORIG_REF_NAME==hdmi_tx_0} -quiet] -quiet

# IP: c:/Users/jkali/ece385/lab7/lab7_1/lab7_1.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_6/src/clk_wiz_0_3/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: c:/Users/jkali/ece385/lab7/lab7_1/lab7_1.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_6/src/clk_wiz_0_3/clk_wiz_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/jkali/ece385/lab7/lab7_1/lab7_1.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_6/src/clk_wiz_0_3/clk_wiz_0_ooc.xdc

# IP: c:/Users/jkali/ece385/lab7/lab7_1/lab7_1.srcs/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_6/mb_usb_hdmi_text_controller_0_6.xci
# IP: The module: 'mb_usb_hdmi_text_controller_0_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/jkali/ece385/lab7/lab7_1/lab7_1.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_6/src/hdmi_tx_0_2/hdmi_tx_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_tx_0 || ORIG_REF_NAME==hdmi_tx_0} -quiet] -quiet

# IP: c:/Users/jkali/ece385/lab7/lab7_1/lab7_1.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_6/src/clk_wiz_0_3/clk_wiz_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: c:/Users/jkali/ece385/lab7/lab7_1/lab7_1.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_6/src/clk_wiz_0_3/clk_wiz_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/jkali/ece385/lab7/lab7_1/lab7_1.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_6/src/clk_wiz_0_3/clk_wiz_0_ooc.xdc
