# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/jkali/ece385/lab7/lab7_1/lab7_1.srcs/sources_1/bd/mb_usb/ip/mb_usb_xbar_2/mb_usb_xbar_2.xci
# IP: The module: 'mb_usb_xbar_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jkali/ece385/lab7/lab7_1/lab7_1.gen/sources_1/bd/mb_usb/ip/mb_usb_xbar_2/mb_usb_xbar_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_usb_xbar_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/jkali/ece385/lab7/lab7_1/lab7_1.srcs/sources_1/bd/mb_usb/ip/mb_usb_xbar_2/mb_usb_xbar_2.xci
# IP: The module: 'mb_usb_xbar_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jkali/ece385/lab7/lab7_1/lab7_1.gen/sources_1/bd/mb_usb/ip/mb_usb_xbar_2/mb_usb_xbar_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_usb_xbar_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
