# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/lab7_1/mb_usb_hdmi_top.xdc

# Block Designs: bd/mb_usb/mb_usb.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb || ORIG_REF_NAME==mb_usb} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_microblaze_0_4/mb_usb_microblaze_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_microblaze_0_4 || ORIG_REF_NAME==mb_usb_microblaze_0_4} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_dlmb_v10_4/mb_usb_dlmb_v10_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_dlmb_v10_4 || ORIG_REF_NAME==mb_usb_dlmb_v10_4} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_ilmb_v10_4/mb_usb_ilmb_v10_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_ilmb_v10_4 || ORIG_REF_NAME==mb_usb_ilmb_v10_4} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_dlmb_bram_if_cntlr_4/mb_usb_dlmb_bram_if_cntlr_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_dlmb_bram_if_cntlr_4 || ORIG_REF_NAME==mb_usb_dlmb_bram_if_cntlr_4} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_ilmb_bram_if_cntlr_4/mb_usb_ilmb_bram_if_cntlr_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_ilmb_bram_if_cntlr_4 || ORIG_REF_NAME==mb_usb_ilmb_bram_if_cntlr_4} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_lmb_bram_4/mb_usb_lmb_bram_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_lmb_bram_4 || ORIG_REF_NAME==mb_usb_lmb_bram_4} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_xbar_2/mb_usb_xbar_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_xbar_2 || ORIG_REF_NAME==mb_usb_xbar_2} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_microblaze_0_axi_periph_4/mb_usb_microblaze_0_axi_periph_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_microblaze_0_axi_periph_4 || ORIG_REF_NAME==mb_usb_microblaze_0_axi_periph_4} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_microblaze_0_axi_intc_4/mb_usb_microblaze_0_axi_intc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_microblaze_0_axi_intc_4 || ORIG_REF_NAME==mb_usb_microblaze_0_axi_intc_4} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_microblaze_0_xlconcat_3/mb_usb_microblaze_0_xlconcat_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_microblaze_0_xlconcat_3 || ORIG_REF_NAME==mb_usb_microblaze_0_xlconcat_3} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_mdm_1_4/mb_usb_mdm_1_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_mdm_1_4 || ORIG_REF_NAME==mb_usb_mdm_1_4} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_clk_wiz_1_4/mb_usb_clk_wiz_1_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_clk_wiz_1_4 || ORIG_REF_NAME==mb_usb_clk_wiz_1_4} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_rst_clk_wiz_1_100M_4/mb_usb_rst_clk_wiz_1_100M_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_rst_clk_wiz_1_100M_4 || ORIG_REF_NAME==mb_usb_rst_clk_wiz_1_100M_4} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_axi_uartlite_0_2/mb_usb_axi_uartlite_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_axi_uartlite_0_2 || ORIG_REF_NAME==mb_usb_axi_uartlite_0_2} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_6/mb_usb_hdmi_text_controller_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_hdmi_text_controller_0_6 || ORIG_REF_NAME==mb_usb_hdmi_text_controller_0_6} -quiet] -quiet

# XDC: c:/Users/jkali/ece385/lab7/lab7_1/lab7_1.gen/sources_1/bd/mb_usb/mb_usb_ooc.xdc
